### ISSUE TITLE
FAIR check - resource identifier

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#10]
The FAIR F1 Guideline states that metadata and date should have a globally unique and persistent identifier. For EML, this XPath is used:
 ```
/eml/dataset/*[@scope="system"]/@id
```

Since the attribute `scope="system"` is specified in the XPath predicate, this id will be unique within the system specified. 

However, since the id is not specified as a URL, there is no guarantee that this id is globally unique, and the id is not resolvable.

**Comment by mbjones** [comment]
The /eml/@packageId is the appropriate path for the global identifier for
the data package.

**Comment by gothub** [comment]
This check (`ResourceIdentifier`) is looking at the identifiers for the data entities, so for example, the id from this path would be selected:
```
<eml:eml><dataset><otherEntity id="urn:uuid:7098ba54-ca6f-4e35-beb3-718bd0fe58a8" scope="system" system="https://arcticdata.io">
```

For the `MetadataIdentifier` check, the  XPath `/eml/@packageId` is being used.

**Comment by gothub** [comment]
Note that potentially many documents are currently have `scope="document"` for this element, when the identifiers are actually DataONE ids (URNs). I don't know how many documents currently are affected.

**Comment by mbjones** [comment]
I wouldn't worry about scope -- I think virtually nobody really uses or
understands it.

**Comment by gothub** [comment]
OK, that makes things easier. Use of the `scope` attribute has been discontinued in commit 0814519bac12ddbebe80ecaf1f50ab76a69a15d1
