### ISSUE TITLE
Integration with ESS-DIVE Zenhub Board

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metadig-checks#102]
## Description

ESS-DIVE collaboration would like to integrate issues submitted to metadig-checks with the ESS-DIVE Collaboration [Zenhub board](https://app.zenhub.com/workspaces/ess-dive-collaboration-5cf01ced95239969104c4cf2/board?repos=11430000,171057454,118799500,171434465,180883980,171454308,171747634,178134572).  

## Procedure

In order to do this we would need to add the following to this repository

#### ESS-DIVE Dev Members
Give access to the follow members so that they may manage ESS-DIVE labels.
- @vchendrix 
- Hesham Elbashandy
- Cory Snavely

#### Labels
The following labels all have specific colors too (see metacatUI or metacat repos)
- ESS-DIVE
- ESS-DIVE:* 
- Priority: Critical
- Priority: High
- Priority: Normal
- Priority: Low

#### ESS-DIVE Milestones
Milestones for our fiscal year deliverables. See examples below.
- ESS-DIVE: FY2019Q4 (September 30)
- ESS-DIVE: FY2020Q1 (December 31)

WRT Priority labels: It is recognized that ESS-DIVE priorities might differ from NCEAS. In cases where an ESS-DIVE member sets a priority on an issue it will be expected that a discussion must occurr to make sure that our priorities are aligned.

**Comment by gothub** [comment]
@vchendrix this all looks good to me, esp. since you have already worked through these details in the other NCEAS repos. What do you think @mbjones ?

**Comment by vchendrix** [comment]
ping @mbjones @gothub.  Do we have a green light on this?

**Comment by vchendrix** [comment]
@mbjones @gothub one change to the above description is that I think Joan needs to also be added to the metadig-checks repository so that she can assign labels etc.

**Comment by tedhabermann** [comment]
Would like to see a link to ESS-DIVE and a description of why this is a good idea.

**Comment by mbjones** [comment]
@vchendrix I added a new Team for ESS-DIVE with Triage permissions so you can add and mannage the ESS-DIVE labels.  But for this repository, please do not add the Priority labels, as there will be many priorities for different groups, and I don't want ESS-DIVE's priorities to be the main ones shown here.  If anything, the main priorities should be the FAIR priorities, which are not specific to one repository.

**Comment by vchendrix** [comment]
@mbjones Thanks! We will stick to the ESS-DIVE labels.

**Comment by vchendrix** [comment]
@mbjones Triage permissions do not work in Zenhub nor do they allow me to manage labels.

**Comment by mbjones** [comment]
Uggg.  Every time we decide to use a tool like ZenHub I regret it.  I changed it to write permission. Please do not push to the repository (use pull requests please), and limit your label changes to the ESS-DIVE labels.  Maybe ZenHub will catch up.

**Comment by vchendrix** [comment]
@mbjones Triage is a new feature that is in beta. My guess is Zenhub will take some time to catch up.  I submitted a feature request to them.
