### ISSUE TITLE
entity.attributeDefinition.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#103]
## Description

Check that each attribute has a definition

## Priority

- FAIR: Required

## Issues
- is this check redundant with `entity.definition.sufficient`?
    - No, because `entity.definition` and `entity.attributeDefinition` are different concepts

## Procedure

- for each attribute/variable in an entity, check if a definition sub-element is present
- if any attribute does not have a definition, the check fails
- for each attribute that is non-compliant, list it in the check output

**Comment by cscully-allison** [comment]
Entity description describes the entity as a whole and not a particular column. Accordingly this is not redundant with entity.defintion.sufficent.

**Comment by amilan17** [comment]
How is entity.attributeDescription different from entity.attributeDefinition?

**Comment by mbjones** [comment]
@cscully-allison agreed

@amilan17 I think `entity.attributeDescription` and `entity.attributeDefinition` are probably meant to be the same concept with slightly different terminology.  We should consolidate on one of these concept terms, and I think the `attributeDefinition` language is more illustrative of the desired concept.
