### ISSUE TITLE
definitions of terms needed for all terms

### ISSUE THREAD

**Issue by lpowers67** [NCEAS/metadig-checks#107]
## Description

Briefly summarize what is being checked.

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Required

## Issues
- List of issues to be resolved

## Procedure

Briefly describe the procedure or algorithm to implement the check.

**Comment by tedhabermann** [comment]
A link to the [ESIP Documentation Glossary](http://wiki.esipfed.org/index.php/Concepts_Glossary) was added to the Repository home page. That glossary is open for editing / additions to the whole ESIP community.
