### ISSUE TITLE
Resource Constraints / Rights presence check

### ISSUE THREAD

**Issue by scgordon** [NCEAS/metadig-checks#113]
## Description

“Resource Constraints”  eg  “gmd:MD_LegalConstraints”, A users rights to use the data

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Required

## Issues
Integrate this check into the Access level

## Procedure

presence and potentially test that the data is open access or available for use

**Comment by gothub** [comment]
@scgordon Pls have a look at [dataset.entityLicense.present.xml](https://github.com/NCEAS/metadig-checks/blob/dev-0.2.0/src/checks/dataset.entityLicense.present.xml) and check if this is what you are requesting.

Also note that at the March workshop we discussed this check as belonging to the 'Reusable' category.
