### ISSUE TITLE
resource.publicationDate.timeframe

### ISSUE THREAD

**Issue by JEDamerow** [NCEAS/metadig-checks#116]
## Description

Dataset publication date is not in the future, and hence inaccessible

## Priority

- FAIR: Optional

## Issues
- Should cutoff date be current date or some reasonable time in the future? 

## Procedure

Check that publication date is on or before a certain date (current date or in a certain amount of time in the future)

**Comment by JEDamerow** [comment]
I added this additional check option, related to issue #82

**Comment by gothub** [comment]
@JEDamerow This check is easy enough to implement and I'll write this check today.

I'm just curious about the use case  for this. Is there some reason why a dataset would be uploaded with a future date other than a mistake?

Also, would this check be done on private datasets? I'm assuming that when a dataset is modified to be made publicly accessible, that is when the publication date would be specified and not before, so private datasets wouldn't have an intended publication date 'preset'.

**Comment by JEDamerow** [comment]
@gothub I am not sure how common this is in other repositories, but some authors specify a date in the future so they can use data in one or more publications before it is public. But, they do want the dataset in a repository and have a DOI. This is reasonable, but it means that their data is not yet accessible and should be reflected in a FAIR score.

**Comment by gothub** [comment]
Added in commit f10bb2d837d64fc1c26d3c12318c740a3fdf20e0

Hey @JEDamerow I think this check should be in the 'Finable' category.

**Comment by tedhabermann** [comment]
Is this date the same as an **embargo date** . That is the date after which DataCite a collected must be available, typically by funder mandate. This is common in NSF land... If so, I think it belongs in accessible. 

In DataCite the publication date is the same as the embargo date (DataCite 4.3 Page 16)

"If an embargo period has been in effect, use the date when the embargo period ends. In the case of datasets, "publish" is understood to mean making the data available on a specific date to the community of researchers. If there is no standard publication year value, use the date that would be preferred from a citation perspective."

**Comment by gothub** [comment]
@tedhabermann @JEDamerow DataONE doesn't limit access based on the publication date. I don't see how search is affected either, as searching for datasets after a certain date isn't affected. 

So, I'm still voting for `Findable`, unless you guys think it should be otherwise.

**Comment by mbjones** [comment]
The `publicationDate` concept is used to display citations and in search systems, and so I think this is a Findable property.  A dataset is not really published until it is publicly accessible.  Maybe we could define the two concepts like this:

- `publicationDate`: the date on which a resource became publicly accessible (thus, can not be in the future). 'Publicly' does not exclude requiring fees or other constraints on access, but does mean that there is a mechanism for most people to access the resource.
- `embargoDate`: the date on which a resource will have become publicly accessible (and thus could be in the future, or the past.  If the `embargoDate` has passed, then it should be equal to the `publicationDate`

**Comment by gothub** [comment]
During the FAIR suite 0.3.0 process, this check produced the following error for pid
urn:uuid:1cc40c25-5e85-4717-8a96-54ab28bf7e53:
```
Error in charToDate(x) : character string is not in a standard unambiguous format Calls: as.Date -> as.Date.character -> charToDate Execution halted
```
In addition, this check returned a check "ERROR", when it should have returned a FAILURE.

For this R check, the `as.Date` function is supposed to not return an error if the parameter 'optional' is used. This mechanism didn't work and the check would return ERROR if either 'TRUE' or 'FALSE' were specified, so error handling was added to the check.

Also, additional data formats to try were added to the check.

These changes were made in commit b900bb342301673112f9a671fe24a4a8809c26f0
