### ISSUE TITLE
check.entity.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#126]
## Description

Check if one or more data entities are specified in the metadata

## Priority

- ADC, ESS-DIVE, KNB: Optional

## Issues
- No known issues

## Procedure

- check if any data entity elements are present, i.e. (dataTable, otherEntity, etc)
- if none are present, the check fails

**Comment by JEDamerow** [comment]
@gothub @mbjones Does this have a corresponding FAIR check? Should this be an accessible check? 

Is this the check for at least one data entity, which also provides the number of entities in the output for current Quality Reports? In reviewing quality reports from datasets, I have found that the number of entities does not always correspond to the actual number included with the package.

**Comment by gothub** [comment]
@JEDamerow I will include this check into the ESS-DIVE 1.1.0 suite, which is noted as 'File present' on the [ESS-DIVE Suite issue](https://github.com/NCEAS/metadig-checks/issues/423). 

This specific check is not in the FAIR suite, however there are several other similar checks:
- entity.name.present
- entity.format.present
- entity.type.present

These checks all are of type 'Interoperable' in the FAIR suite, so I'll make it the same for the ESS-DIVE suite.

**Comment by gothub** [comment]
This check was added to the ESS-DIVE suite in commit e7570458b8b8b3855ecbd76f31597514b83ca619
