### ISSUE TITLE
FAIR check - service provider

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#13]
The `ServiceProvider` check uses the following XPath:
```
/*/identificationInfo/SV_ServiceIdentification/pointOfContact/CI_ResponsibleParty/individualName | 
/*/identificationInfo/SV_ServiceIdentification/pointOfContact/CI_ResponsibleParty/organisationName | 
/*/identificationInfo/SV_ServiceIdentification/pointOfContact/CI_ResponsibleParty/positionName
```

I haven't found any documents from NCEI, RW or PANGAEA that use this element.

In addition, I don't see this concept expressed in EML.

Do we really need this check in the FAIR suite?

**Comment by amoeba** [comment]
What's the source in the list of FAIR principles for this check? DataONE's index schema has various fields related to services. For example, the `isService` field is defined for ISO* docs as,

```
//srv:SV_ServiceIdentification or //gmd:distributionInfo/gmd:MD_Distribution
```

and for EML as:

```
//software/implementation/distribution/online/url
```

(Not entirely sure those make sense). There are [580,223](https://search.dataone.org/cn/v2/query/solr/?q=isService:true&fl=id,isService) docs where that field is set to true.

**Comment by gothub** [comment]
This check would be within the `Accessible` category, and you could say that it extends this category, as there isn't an exact correspondence to the guidelines.

**Comment by gothub** [comment]
This check is now discussed in https://github.com/NCEAS/metadig-checks/issues/89
