### ISSUE TITLE
Review score calculation

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig-checks#155]
Let's talk about the scoring issue that was raised in #149.  I think what we want is that datasets pass all of the 'required' checks, and as many of the optional checks as possible. Thus, our current algorithm is designed to count required checks against the score when they pass or fail, but include optional checks only when they pass.  This means that passed optional checks will increase a score (effectively diluting the effect of any failing required checks).  So the formula would be:

![CodeCogsEqn](https://user-images.githubusercontent.com/766407/68729238-e46eca80-0575-11ea-8d3a-c5573f2ab2e8.png)

Here's a table of some example results:

Required Passed | Required Failed  |  Optional Passed  | Optional Failed  | Score
----------------- | ---------------- | ----------------- | ---------------- | ------
10 | 0 | 0 | 0 | 100%
8 | 2 | 0 | 0 | 80%
8 | 2 | 10 | 0 | 90%
8 | 2 | 0 | 10 | 80%
8 | 2 | 5 | 5 | 87%
10 | 0 | 5 | 5 | 100%

Does this make sense to you @gothub, and coincide with what you have implemented?

**Comment by mbjones** [comment]
@jeanetteclark does that seem intuitive to you as well?

**Comment by jeanetteclark** [comment]
This makes sense but I don't think your table has the correct math. You show:

|Required Passed	|Required Failed|	Optional Passed|	Optional Failed|	Score|
|--|--|--|--|--|
|8|	2|	10|	0|	80%|
|8|	2|	0|	10|	90%|

according to your equation the top row should get (8+10)/(8+2+10) = 90%
the bottom row is (8+0)/(8+2+0) = 80%

The good news is, that makes sense to me with the corrected math. A dataset that passes optional checks gets a higher score than the dataset with equivalent required checks that fails optional checks, which makes sense.

**Comment by mbjones** [comment]
Good catch @jeanetteclark -- I had those backwards when I transcribed my notes.  I fixed the table now.

**Comment by gothub** [comment]
@mbjones @jeanetteclark yes - the score calculation uses the formula that you show above, once the 'skip' behavior has been removed from the FAIR checks.

**Comment by mbjones** [comment]
OK, great.  We can leave this issue open for a bit to see if other comments on the algorithm come in. But then you can go ahead and close it when you have removed the SKIP effect from the calculations.

**Comment by gothub** [comment]
The "SKIP" effect was removed from the FAIR checks in commit 323d1c9862c2c8b29edad149a4b3a785176ca85f
