### ISSUE TITLE
ORCID check has wrong regex

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metadig-checks#157]
The check for an ORCID seems to have a copy/paste error and the regex seems to be checking for a DOI rather than an ORCID.  See the code on Line 33:

https://github.com/NCEAS/metadig-checks/blob/b25c712b13d75e254c449c2553f8deb3a8235d67/src/checks/contact.has.orcid.xml#L33

**Comment by gothub** [comment]
Fixed in commit fdd24b39bd231a80697c2837c5c1ac1de29e9757
