### ISSUE TITLE
Non-proprietary format check

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#23]
For the check 'NonProprietaryEntittyFormat', what lists should be used for `proprietary` and `non-proprietary` formats?

**Comment by amoeba** [comment]
Sounds like a tough check to get right from the user's perspective. However, I think a really good approach would be to not find or create a list of non-proprietary formats since there are so many but to instead try to find common proprietary formats such as MS Excel and MS Access files and fail the check of those are found.

When the check passes, the message could indicate that the passing grade isn't the same thing as "you have not used any proprietary formats". What do you think?

**Comment by gothub** [comment]
Sounds reasonable. Finding the list of proprietary formats may just mean assembling it ourselves.

**Comment by amoeba** [comment]
Yeah, maybe the NCEAS Data Team would be able to scrap together a short list of what they usually deal with and us developers could fill in any others they don't have much contact with.

**Comment by mbjones** [comment]
We could start by going through the DataONE formatId list and marking each format ass proprietary or open or unknown/mixed.  That should cover all of the files we have in DataONE.

**Comment by gothub** [comment]
Here is a list of formats from http://cn.dataone.org/cn/v2/query/solr/?q=formatType:DATA&facet=true&facet.field=formatId&facet.mincount=1&rows=0

Please mark formats that are proprietary:

- [ ] image/jpeg
- [ ] application/octet-stream
- [ ] text/csv
- [ ] audio/x-wav
- [ ] image/png
- [ ] text/plain
- [ ] text/xml
- [ ] application/pdf
- [ ] image/tiff
- [ ] image/gif
- [ ] netCDF-4
- [ ] netCDF-3
- [ ] application/x-gzip
- [ ] application/zip
- [ ] application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
- [ ] application/vnd.ms-excel
- [ ] application/x-bzip2
- [ ] application/x-fasta
- [ ] application/x-tar
- [ ] text/html
- [ ] application/vnd.openxmlformats-officedocument.wordprocessingml.document
- [ ] application/xml
- [ ] CF-1.4
- [ ] application/msword
- [ ] application/x-rar-compressed
- [ ] application/vnd.google-earth.kml+xml
- [ ] application/R
- [ ] application/x-python
- [ ] application/rtf
- [ ] video/avi
- [ ] video/mp4
- [ ] application/mathematica
- [ ] text/tsv
- [ ] application/SAS
- [ ] video/quicktime
- [ ] application/vnd.google-earth.kmz
- [ ] application/vnd.openxmlformats-officedocument.presentationml.presentation
- [ ] application/postscript
- [ ] video/mpeg
- [ ] text/x-rmarkdown
- [ ] application/MATLAB
- [ ] application/vnd.ms-excel.sheet.binary.macroEnabled.12
- [ ] audio/mpeg
- [ ] image/bmp
- [ ] application/MATLAB-v7
- [ ] application/vnd.ms-powerpoint
- [ ] application/json
- [ ] application/rdf+xml
- [ ] text/markdown

**Comment by mbjones** [comment]
Note that some of those are general types (e.g., application/octet-stream, text/xml) that may or may not be used for defining proprietary application types.  We really should be more specifically typing those when possible. 

Also, Matlab's most recent format is an HDF5 file format, and so is technically not proprietary, but their earlier .mat formats were proprietary, so it varies by version for Matlab.  HDF5 seems to be missing from the list.

**Comment by mbjones** [comment]
Also, the full list of registered formats is here:

https://cn.dataone.org/cn/v2/formats

**Comment by amoeba** [comment]
(@mbjones 	I added a [ticket](https://redmine.dataone.org/issues/8820) for adding HDF 4 and 5 to DataONE's Object formats list.)

**Comment by mbjones** [comment]
Thanks.  And I note that the object format list has 5 formats for Matlab, only one of which would be non-proprietary (`application/MATLAB-v7.3`).

```xml
<objectFormat>
    <formatId>application/MATLAB</formatId>
    <formatName>MATLAB programming language script</formatName>
    <formatType>DATA</formatType>
    <mediaType name="text/x-matlab"/>
    <extension>m</extension>
</objectFormat>
<objectFormat>
    <formatId>application/MATLAB-v7.3</formatId>
    <formatName>Mathworks MATLAB version 7.3 (R2006b or later) binary file - HDF5 compatible</formatName>
    <formatType>DATA</formatType>
    <mediaType name="application/octet-stream"/>
    <extension>mat</extension>
</objectFormat>
<objectFormat>
    <formatId>application/MATLAB-v7</formatId>
    <formatName>Mathworks MATLAB version 7 (R14 or later) binary file</formatName>
    <formatType>DATA</formatType>
    <mediaType name="application/octet-stream"/>
    <extension>mat</extension>
</objectFormat>
<objectFormat>
    <formatId>application/MATLAB-v6</formatId>
    <formatName>Mathworks MATLAB version 6 (R8 or later) binary file</formatName>
    <formatType>DATA</formatType>
    <mediaType name="application/octet-stream"/>
    <extension>mat</extension>
</objectFormat>
<objectFormat>
    <formatId>application/MATLAB-v4</formatId>
    <formatName>Mathworks MATLAB version 4 binary file</formatName>
    <formatType>DATA</formatType>
    <mediaType name="application/octet-stream"/>
    <extension>mat</extension>
</objectFormat>
```

**Comment by gothub** [comment]
Here is the full list from DataONE formats service:

- [ ] "ATOM-1.0", http://www.w3.org/2005/Atom, application/atom+xml, atom
- [ ] "AnnotatorJS 1.2.x Annotation model", http://docs.annotatorjs.org/en/v1.2.x/annotation-format.html, application/json, json
- [ ] "BagIt File Packaging Format Version 0.97", application/bagit-097,,
- [ ] "Bitmap Image File", image/bmp, image/bmp, bmp, N
- [ ] "Bzip2 Compressed File", application/x-bzip2, application/x-bzip2, zip
- [ ] "Comma Separated Values Text", text/csv, text/csv, csv
- [ ] "Content Standard for Digital Geospatial Metadata, Biological Data Profile, version 001.1-1999", FGDC-STD-001.1-1999, text/xml, xml
- [ ] "Content Standard for Digital Geospatial Metadata, Metadata Profile for Shoreline Data, version 001.2-1999", FGDC-STD-001.2-1999, text/xml, xml
- [ ] "Content Standard for Digital Geospatial Metadata, version 001-1998", FGDC-STD-001-1998, text/xml, xml
- [ ] "Darwin Core, version 2.0", http://digir.net/schema/conceptual/darwin/2003/1.0/darwin2.xsd, text/xml, xml
- [ ] "Data Documentation Initiative, Codebook version 2.1", http://www.icpsr.umich.edu/DDI, text/xml, xml
- [ ] "Data Documentation Initiative, Codebook version 2.5", ddi:codebook:2_5, text/xml, xml
- [ ] "DataCite Metadata Schema version 3.0", http://datacite.org/schema/kernel-3.0, text/xml, xml
- [ ] "DataCite Metadata Schema version 3.1", http://datacite.org/schema/kernel-3.1, text/xml, xml
- [ ] "DataONE Dublin Core Extended v1.0", http://ns.dataone.org/metadata/schema/onedcx/v1.0, text/xml, xml
- [ ] "Dryad Metadata Application Profile Version 3.0", http://purl.org/dryad/terms/, text/xml, xml
- [ ] "Dryad Metadata Application Profile Version 3.1", http://datadryad.org/profile/v3.1, text/xml, xml
- [ ] "Ecological Metadata Language, Access module, version 2.0.0beta4", -//ecoinformatics.org//eml-access-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Access module, version 2.0.0beta6", -//ecoinformatics.org//eml-access-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Attribute module, version 2.0.0beta4", -//ecoinformatics.org//eml-attribute-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Attribute module, version 2.0.0beta6", -//ecoinformatics.org//eml-attribute-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Constraint module, version 2.0.0beta4", -//ecoinformatics.org//eml-constraint-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Constraint module, version 2.0.0beta6", -//ecoinformatics.org//eml-constraint-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Coverage module, version 2.0.0beta4", -//ecoinformatics.org//eml-coverage-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Coverage module, version 2.0.0beta6", -//ecoinformatics.org//eml-coverage-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Dataset module, version 2.0.0beta4", -//ecoinformatics.org//eml-dataset-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Dataset module, version 2.0.0beta6", -//ecoinformatics.org//eml-dataset-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Distribution module, version 2.0.0beta4", -//ecoinformatics.org//eml-distribution-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Distribution module, version 2.0.0beta6", -//ecoinformatics.org//eml-distribution-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Entity module, version 2.0.0beta4", -//ecoinformatics.org//eml-entity-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Entity module, version 2.0.0beta6", -//ecoinformatics.org//eml-entity-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Literature module, version 2.0.0beta4", -//ecoinformatics.org//eml-literature-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Literature module, version 2.0.0beta6", -//ecoinformatics.org//eml-literature-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Party module, version 2.0.0beta4", -//ecoinformatics.org//eml-party-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Party module, version 2.0.0beta6", -//ecoinformatics.org//eml-party-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Physical module, version 2.0.0beta4", -//ecoinformatics.org//eml-physical-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Physical module, version 2.0.0beta6", -//ecoinformatics.org//eml-physical-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Project module, version 2.0.0beta4", -//ecoinformatics.org//eml-project-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Project module, version 2.0.0beta6", -//ecoinformatics.org//eml-project-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Protocol module, version 2.0.0beta4", -//ecoinformatics.org//eml-protocol-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Protocol module, version 2.0.0beta6", -//ecoinformatics.org//eml-protocol-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Resource module, version 2.0.0beta4", -//ecoinformatics.org//eml-resource-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Resource module, version 2.0.0beta6", -//ecoinformatics.org//eml-resource-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Software module, version 2.0.0beta4", -//ecoinformatics.org//eml-software-2.0.0beta4//EN, text/xml, xml
- [ ] "Ecological Metadata Language, Software module, version 2.0.0beta6", -//ecoinformatics.org//eml-software-2.0.0beta6//EN, text/xml, xml
- [ ] "Ecological Metadata Language, version 2.0.0", eml://ecoinformatics.org/eml-2.0.0, text/xml, xml
- [ ] "Ecological Metadata Language, version 2.0.1", eml://ecoinformatics.org/eml-2.0.1, text/xml, xml
- [ ] "Ecological Metadata Language, version 2.1.0", eml://ecoinformatics.org/eml-2.1.0, text/xml, xml
- [ ] "Ecological Metadata Language, version 2.1.1", eml://ecoinformatics.org/eml-2.1.1, text/xml, xml
- [ ] "Extensible Markup Language Application", application/xml, application/xml, xml
- [ ] "Extensible Markup Language", text/xml, text/xml, xml
- [ ] "FASTA sequence file", application/x-fasta, application/x-fasta, fasta
- [ ] "GZIP Format", application/x-gzip, application/x-gzip, gz
- [ ] "Geographic MetaData (GMD) Extensible Markup Language", http://www.isotc211.org/2005/gmd, text/xml, xml
- [ ] "Google Earth Keyhole Markup Language (KML) Compressed archive", application/vnd.google-earth.kmz, application/vnd.google-earth.kmz, kmz
- [ ] "Google Earth Keyhole Markup Language (KML)", application/vnd.google-earth.kml+xml, application/vnd.google-earth.kml+xml, kml
- [ ] "Graphics Interchange Format", image/gif, image/gif, gif
- [ ] "Hypertext Markup Language", text/html, text/html, html
- [ ] "JPEG 2000", image/jp2, image/jp2, jpg
- [ ] "JPEG", image/jpeg, image/jpeg, jpg
- [ ] "JavaScript Object Notation (JSON) Linked Data file", application/json-ld, application/ld+json, json
- [ ] "JavaScript Object Notation (JSON) file", application/json, application/json, json
- [ ] "Kernel Metadata and Electronic Resource Citations (ERCs), 2010.05.13", anvl/erc-v02, text/anvl, anvl
- [ ] "MATLAB programming language script", application/MATLAB, text/x-matlab, m
- [ ] "MPEG-1 Video", video/mpeg, video/mpeg, mpg
- [ ] "MPEG-1 or MPEG-2 Audio Layer III", audio/mpeg, audio/mpeg, mp3
- [ ] "MPEG-4 Video", video/mp4, video/mp4, mp4
- [ ] "Markdown file (pandoc markdown compatible)", text/markdown, text/markdown, md
- [x] "Mathematica Notebook", application/mathematica, application/mathematica, nb
- [x] "Mathworks MATLAB version 4 binary file", application/MATLAB-v4, application/octet-stream, mat
- [x] "Mathworks MATLAB version 6 (R8 or later) binary file", application/MATLAB-v6, application/octet-stream, mat
- [x] "Mathworks MATLAB version 7 (R14 or later) binary file", application/MATLAB-v7, application/octet-stream, mat
- [ ] "Mathworks MATLAB version 7.3 (R2006b or later) binary file - HDF5 compatible", application/MATLAB-v7.3, application/octet-stream, mat
- [ ] "Metadata Encoding and Transmission Standard, version 1", http://www.loc.gov/METS/, text/xml, xml
- [ ] "Microsoft Audio Video Interleave (AVI) File", video/avi, video/avi, avi
- [x] "Microsoft Excel OpenXML", application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, xlsx
- [x] "Microsoft Excel file format", application/vnd.ms-excel, application/vnd.ms-excel, xls
- [x] "Microsoft Office Excel 2007 binary workbooks", application/vnd.ms-excel.sheet.binary.macroEnabled.12, application/vnd.ms-excel.sheet.binary.macroEnabled.12, xls
- [x] "Microsoft Office OpenXML Presentation", application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.openxmlformats-officedocument.presentationml.presentation, pptx
- [x] "Microsoft Office Powerpoint", application/vnd.ms-powerpoint, application/vnd.ms-powerpoint, ppt
- [x] "Microsoft Word OpenXML", application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.openxmlformats-officedocument.wordprocessingml.document, docx
- [x] "Microsoft Word file format", application/msword, application/msword, doc
- [ ] "N-TRIPLE", http://www.w3.org/TR/rdf-testcases/#ntriples, text/plain, nt
- [ ] "N3", text/n3, text/n3, rdf
- [ ] "NEXUS File Format for Systematic Information", nexus/1997, text/plain, nxs
- [ ] "NOAA Variant Geographic MetaData (GMD) Extensible Markup Language", http://www.isotc211.org/2005/gmd-noaa, text/xml, xml
- [ ] "NeXML 2009", http://www.nexml.org/2009, text/xml, xml
- [ ] "NetCDF Climate and Forecast Metadata Convention, version 1.0", CF-1.0, application/netcdf, nc
- [ ] "NetCDF Climate and Forecast Metadata Convention, version 1.1", CF-1.1, application/netcdf, nc
- [ ] "NetCDF Climate and Forecast Metadata Convention, version 1.2", CF-1.2, application/netcdf, nc
- [ ] "NetCDF Climate and Forecast Metadata Convention, version 1.3", CF-1.3, application/netcdf, nc
- [ ] "NetCDF Climate and Forecast Metadata Convention, version 1.4", CF-1.4, application/netcdf, nc
- [ ] "NetCDF Markup Language, version 2.2", http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2, application/netcdf, nc
- [ ] "Network Common Data Format, version 3", netCDF-3, application/netcdf, nc
- [ ] "Network Common Data Format, version 4", netCDF-4, application/netcdf, nc
- [ ] "North American Profile of ISO 19115: 2003 Geographic Information - Metadata", INCITS-453-2009, text/xml, xml
- [ ] "OAI-PMH Dublin Core v2.0, with online related resource", http://www.openarchives.org/OAI/2.0/oai_dc/, text/xml, xml
- [ ] "Oak Ridge National Lab Mercury Metadata version 1.0", http://purl.org/ornl/schema/mercury/terms/v1.0, text/xml, xml
- [ ] "Object Reuse and Exchange Vocabulary", http://www.openarchives.org/ore/terms, application/rdf+xml, rdf
- [ ] "Octet Stream", application/octet-stream, application/octet-stream, data
- [ ] "PANGAEA Variant Geographic MetaData (GMD) Extensible Markup Language", http://www.isotc211.org/2005/gmd-pangaea, text/xml, xml
- [ ] "Plain Text", text/plain, text/plain, txt
- [ ] "Portable Document Format", application/pdf, application/pdf, pdf
- [ ] "Portable Network Graphics", image/png, image/png, png
- [ ] "Postscript", application/postscript, application/postscript, ps
- [ ] "Python programming language script", application/x-python, text/x-python, py
- [ ] "Quicktime Video", video/quicktime, video/quicktime, mov
- [ ] "R Markdown file (pandoc markdown compatible)", text/x-rmarkdown, text/markdown, Rmd
- [ ] "R programming language script", application/R, text/x-rsrc, R
- [ ] "RAW digital sensor image file", image/x-raw, application/octet-stream, raw
- [ ] "RDF/XML", http://www.w3.org/TR/rdf-syntax-grammar, application/rdf+xml, rdf
- [ ] "RDFa", http://www.w3.org/TR/rdfa-syntax, application/xhtml+xml, xhtml
- [ ] "Resource Description Framework", application/rdf+xml, application/rdf+xml, rdf
- [ ] "Rich Text Format", application/rtf, application/rtf, rtf
- [ ] "Roshal Archive File", application/x-rar-compressed, application/x-rar-compressed, rar
- [x] "SAS programming language script", application/SAS, text/x-sas, sas
- [ ] "Scalable Vector Graphics", image/svg+xml, image/svg+xml, svg
- [ ] "Simple Darwin Core", http://rs.tdwg.org/dwc/xsd/simpledarwincore/, text/xml, xml
- [ ] "TURTLE", text/turtle, text/turtle, ttl
- [ ] "Tab Separated Values Text", text/tsv, text/tab-separated-values, tsv
- [ ] "Tagged Image File Format", image/tiff, image/tiff, tiff
- [ ] "Tape Archive File", application/x-tar, application/x-tar, tar
- [ ] "Water Markup Language, version 1.0", http://www.cuahsi.org/waterML/1.0/, text/xml, xml
- [ ] "Water Markup Language, version 1.0", http://www.cuahsi.org/waterML/1.1/, text/xml, xml
- [ ] "Wave Audio Format", audio/x-wav, audio/x-wav, wav
- [ ] "Windows Media Audio File", audio/x-ms-wma, audio/x-ms-wma, wma
- [ ] "Windows Media Video File", video/x-ms-wmv, video/x-ms-wmv, wmv
- [ ] "Zip file format", application/zip, application/zip, zip

**Comment by mbjones** [comment]
I marked Raw image files as proprietary.  See https://en.wikipedia.org/wiki/Raw_image_format. However, they often contain critical data and metadata that are lost when the images are converted to open formats. Until a universal open Raw format is available, its probably still beneficial for us to capture raw images in addition to open versions, and so I am not sure we should penalize this in the check.  Or maybe we do so and just recognize that there's no good alternative right now, as is similarly true with other binary sensor data formats.

**Comment by gothub** [comment]
Yeah, not sure, but if we flag (FAIL) formats that are not directly usable (without a conversion by the end user) then there is an incentive for the data creator to provide a more usable format.

**Comment by gothub** [comment]
This check is discussed in issue https://github.com/NCEAS/metadig-checks/issues/64
