### ISSUE TITLE
resource.abstractLength.sufficient

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#28]
## Description

Check if the dataset abstract has a sufficient length, counted in words. Minimum word count is currently 4, maximum word count is 20

## Priority

- FAIR: Required

## Issues
- several users have stated that the minimum and maximum word counts should be changed. What should these values be?

## Procedure

Retrieve the title, obtain word count and compare to min, max values.

**Comment by JEDamerow** [comment]
Abstract length in the deployed abstract length check is for at least 100 words with no maximum listed.

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: 
data[*].attributes.descriptions[?(@.descriptionType="Abstract")].description and data[*].attributes.descriptions[?(@.descriptionType="TechnicalInfo")].description

"Abstract" is the most common descriptionType in DataCite, but there are other description types (Methods SeriesInformation TableOfContents TechnicalInfo Other). I included TechnicalInfo, but none of the others after looking at content.

**Comment by JEDamerow** [comment]
Should this check be for minimum of 100 words and linked to implemented check #117 ?
