### ISSUE TITLE
entity.attributeNames.unique

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#35]
## Description

For each data entity in a dataset, check that the attribute names within a data entity are unique.

## Priority

- FAIR: Required

## Issues
- No known issues

## Procedure

- for each data entity in a dataset, check that attribute names are unique

**Comment by smrgeoinfo** [comment]
This either requires that the attributes are described in the metadata (e.g. CSDGM Entity/Attribute metadata), or that the validator GET the data and is able to perform the necessary introspection to determine attribute names.

**Comment by mbjones** [comment]
@smrgeoinfo exactly.  Its a more stringent check than the `entity.attributeNames.present` would be, and assumes the names are in the metadata.  Not sure we want to be pulling attribute metadata out of data entities for this check -- that seems more in the spirit of a metadata-data congruency check that would compare the names in the metadata to the names in the data file (e.g., an `entity.attributeNames.congruent` check).
