### ISSUE TITLE
entity.attributePrecision.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#36]
## Description

Check if a measurement precision has been specified

## Priority

- FAIR: Required

## Issues
- No known issues

## Procedure

- each attribute type that could have a measure precision is check. If any such attribute is found without a precision specified, the check fails and the offending attributes are listed.

**Comment by gepeng86** [comment]
Similar to precision, data uncertainty is also an important quality attribute for data reuse. Should it be included in the checks?

**Comment by mbjones** [comment]
@gepeng86 I think that's a good idea, but could you open a separate issue, and propose how such a check might be evaluated in that ticket?  I don't think we can get it in the next release, but let's get the discussion going on how to evaluate data uncertainty info from the metadata.  I think these are mostly text fields in most standards, so probably all we can do is check for presence/absence automatically. Please propose what you are thinking.

**Comment by gepeng86** [comment]
Thank you, Matt, for your feedback.

Opening a separate issue sounds good to me. Checking for presence/absence
of data uncertainty information is a good approach.

It is okay not getting into the current release - I am still not familiar
with GitHub and it may take a while for me to create an issue.

As a heads-up,  I'll be sending you and Ted an email on a potential
presentation on MetaDIG for an IQC session/workshop at the ESIP 2020 summer
meeting in next July.

Best regards,

--- Peng

**Comment by gothub** [comment]
This check was incorrectly performing an additional check on the precision value returned from the XPath selector by attempting to convert to a numeric value. This is an invalid check and has been removed, as EML /eml/dataset/*/attributeList/attribute/measurementScale/dateTime can be a string value, which may not convert to a number, i.e. '30 minutes', which I believe is valid.

This addtional check has been removed in commit b1a426e13e455beaf88ee5ca7e93b2eab0c472e0
