### ISSUE TITLE
Clarify quality report messages for ESS-DIVE suite of checks

### ISSUE THREAD

**Issue by JEDamerow** [NCEAS/metadig-checks#360]
There are some typos and inconsistencies in structure and content of quality report messages for the ESS-DIVE suite of automated checks. We would like some minor edits to quality report messages, for presentation and clarity. 

**contact identifier**
- Current fail message: A user identifier for any contact is not present, unable to check for an ORCID.  Change to: No ORCID is provided for the contact person.

**keywords minimum**
- Current pass message: 29 keywords present (minumum is 3).   Change to: 29 keywords are present, which is above the minimum of 3 keywords.
- Current fail message: 2 keywords present (minumum is 3)  Change to: Only 2 keywords are present, and 3 or more keywords are required.

**keywords in title (optional)** 
- Current WARNING message: the keywords 'Changes, Carbon, cultivation, after' were found in the title .  Change to: The keywords 'Changes, Carbon, cultivation, after' were also found in the title.

**title** 
- Current pass message: The title length word count of 9 is sufficient (between 7 and 40 words). Change to: The title contains 9 words, which is sufficient. 
- Current fail message: The title word count of 2 is less than the required minimum of 7 .    Change to: The title is only 2 words long, and 7-40 words are required.

**abstract** 
- Current fail message: The abstract is only 98 word(s) long but 100 or more is required. 
 Change to: The abstract is only 98 words long, and 100 or more words are required.

**temporal coverage**
- Current fail message: A description of this dataset's temporal coverage is not present.    Change to: Start and end dates describing the temporal coverage of this dataset are not present.  

**geographic coverage and coordinates** - change to optional
- Current fail message: A set of bounding coordinates describing the geographic coverage of this dataset is not present.  Change to: Coordinates describing the point location or geographic area of this dataset are not present.

**methods**
- Current fail message: A methods section is not present, so unable to check method step descriptions word count.  Change to: A methods section is not present. We recommend fully outlining all methods used to produce your data package.

**Comment by gothub** [comment]
Fixed in commit cd68a63656e6abfee6f1ed7e273a2a0fedd364ae
