### ISSUE TITLE
changes to make to the entity.identifier.present, entity.identifier.resolvable, and resource.distribution.present checks

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-checks#374]
## Description

Improvements for these checks and reducing redundancy

## Procedure

- entity.identifier.present: should check for presence either in `[entity]/@id` or `[entity]/physical/distribution/url`
- entity.identifier.resolves: should check for resolution in`[entity]/physical/distribution/url`
- resource.distribution.present: should only check in `dataset/distribution/url` and not in the entities (removes redundancy, and resource is metadata not data)

**Comment by gothub** [comment]
@jeanetteclark thanks for these check corrections, they will be in the next FAIR suite release. However, `entity.identifier.resolves` will be removed, as described [here](https://github.com/NCEAS/metadig-checks/issues/373)

**Comment by jeanetteclark** [comment]
I think on the Arctica call we changed our minds. @mbjones can you confirm?

**Comment by mbjones** [comment]
I can confirm that I think Jeanette's proposal makes sense to me, and should replace our prior discussion.

**Comment by jeanetteclark** [comment]
as an addendum:

resource.landingPage.present: should only check in dataset/distribution/url and not in the entities (resource is metadata not data)

**Comment by gothub** [comment]
@jeanetteclark how does the Arctica call affect this issue (from the comments above)?

Also, for `entity.identifier.present`, are you saying that for the path `[entity]/physical/distribution/url`, the last portion of the path has to be an identifier?

**Comment by jeanetteclark** [comment]
My original description of the issue matches what we decided on the Arctica call

I believe that the identifier is meant to be represented by the entire URI, @mbjones can you confirm?

**Comment by mbjones** [comment]
That matches my take on it too.

**Comment by gothub** [comment]
Thx for the clarification.

The following updates have been make:
- entity.identifier.present updated in commit 49e445c5e0558144498a7a58ea6f482b0bff7350
  - include xpath for entity`./physical/distribution/url`
- entity.identifier.resolvable removed from FAIR suite in commit 3a8d4a647fc9afb244f3e26d96c0e9ff328c8295
- resource.distribution.present updated in commit b3844645399978e9a23046295697cea0d1a6208a
  - removed entity `./physical/distribution/url` xpath
- resource.landingPage.present updated in commit 7f07670f91ac2322eaf36234d5a124cb90cba066
  - removed entity `./physical/distribution/url` xpath

**Comment by jeanetteclark** [comment]
@gothub I think we got some wires crossed on entity.identifier.resolvable

From above:

`entity.identifier.resolveable`: should check for resolution in[entity]/physical/distribution/url

**Comment by gothub** [comment]
@jeanetteclark this check was done as a result of a conversation in slack. It was my understanding that this check should be removed entirely:

https://github.com/NCEAS/metadig-checks/issues/373

**Comment by gothub** [comment]
OK - instead of removing `entity.identifier.resolvable`, rename it to `entity.distributionUrl.resolvable` and check the entity distribution url for resolvability. For EML, this is `/eml/dataset/[entity]/physical/distribution/online/url`.

What is the current thinking on requiring the `<url function="download">` attribute? Should this be included or not?

**Comment by gothub** [comment]
See https://github.com/NCEAS/metadig-checks/issues/379 for a resolution on `entity.identifier.resolvable`
