### ISSUE TITLE
entity.attributeMeasurementScale.present seems to fail for dateTime attributes

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-checks#376]
## Description

I'm not sure why, but it seems like the `dateTime` `measurementDomain` is not being picked up by the check. This check fails for date attributes only.

## Issues

- Ensure `entity.attributeMeasurementScale.present` succeeds if any of the `measurementScales` are present (dateTime, interval, nominal, ordinal, ratio)

Here are two examples:

https://test.arcticdata.io/quality/urn%3Auuid%3A9050c8da-f55d-4709-8c52-2990c1d749a6
https://test.arcticdata.io/quality/urn%3Auuid%3A026ea3ef-809c-4c4b-9c38-1c7587641a6f

**Comment by gothub** [comment]
@jeanetteclark looking at the two metadata docs that you reference, it looks like the check that is failing is entity.attributeDomain.present. This check is a bit more specific than entity.attributeMeasurementScale.present.

the domain check is looking for the presence of the path `/measurementScale/dateTime/dateTimeDomain`, which doesn't exist for the `./attribute/measurementScale/dateTime` entries in the referenced documents.

See https://eml.ecoinformatics.org/images/eml-attribute.png

**Comment by jeanetteclark** [comment]
Ah - now that I know which check we are talking about, I can confirm that this is a valid (though strict!) check

**Comment by jeanetteclark** [comment]
@mbjones followed up on slack:

> For interval and ratio types, the domain is determined via numberType, and would be restricted via bounds. For dateTime, the domain is implicit, and would be restricted via bounds. I think the check should be parallel i.e., not require a more restrictive domain for dates than it does for numbers

I think this makes sense, so the check should just look in `/eml/dataset/*/attributeList/attribute/measurementScale/dateTime`

**Comment by gothub** [comment]
Updated check xpath for dateTime to
```
/eml/dataset/*/attributeList/attribute/measurementScale/dateTime
```
Updated in commit 6f060e0b59b3f67e4b63db8468d613d40c47b60c
