### ISSUE TITLE
Update EML id for entity.identifier.resolvable

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#379]
@mbjones @jeanetteclark

For EML, the check `entity.identifier.resolvable` uses these XPaths as the resolvable identifer:
```
/eml/dataset/*[self::dataTable|self::spatialRaster|self::spatialVector|self::storedProcedure|self::view|self::otherEntity]/@id |
/eml/dataset/*/alternateIdentifier
```
Per our recent Slack conversation, these XPaths will be replaced with
```
/eml/dataset/*/physical/distribution/online/url[@function="download"]
```

**Comment by gothub** [comment]
Since entity.identifier.resolvable is being updated to use the distribution url as the resolvable identifier, we may wish to update the XPaths for ISO to now use the distribution url, and rename this check to `entity.distributiionURL.resolvable`, for consistency

**Comment by mbjones** [comment]
That sounds good.

**Comment by gothub** [comment]
Updated check in commit 252ee33d95ff698ae6f1668d72c7182978a27416
