### ISSUE TITLE
NSF Award not recognized

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/metadig-checks#380]
## Description

The NSF award check failed for a particular award. However, we were able to get the information about it from the NSF awards database using `arcticdatautils::eml_nsf_to_project()` without any issue.

## Priority

- FAIR: Optional

## Procedure
This happened in this dataset where there was one award that was not recognized in the assessment report:
https://arcticdata.io/catalog/quality/urn%3Auuid%3Aa8b680c8-8dff-4c35-8c4c-91c5cba04038

This is the award number: 1523025. The award title is:
Doctoral Dissertation Improvement Grant: The Archaeological Investigation of Erosion and its Effect on Social Processes in the Arctic

**Comment by jeanetteclark** [comment]
Just to clarify - the check fails on the structured funding information that EML 2.2.0 supports

**Comment by mbjones** [comment]
Thanks! Looks like one definitely needing a fix. @gothub is the issue obvious to you?
