### ISSUE TITLE
Check for "Provenance Trace Present" returns SUCCESS when not present

### ISSUE THREAD

**Issue by cwbeltz** [NCEAS/metadig-checks#382]
## Description
Check for "Provenance Trace Present" returns SUCCESS even when information is not present. This occurs on line 23 in
 `provenance.trace.present.xml`.

## Issues
When "provenance trace information was not found" the status is set to "SUCCESS". This likely should be changed to "FAILURE".

<img width="745" alt="Screen Shot 2020-10-29 at 3 13 22 PM" src="https://user-images.githubusercontent.com/32374186/97621470-521b3d00-19f9-11eb-8d7e-14ba71443eb6.png">

**Comment by mbjones** [comment]
Good catch @cwbeltz . I had wondered why those were so high!

**Comment by gothub** [comment]
Fixed in commit 687f2aee7ad5e97ef9de2014706b0041b5937802.
