### ISSUE TITLE
entity.attributeUnits.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#39]
## Description

Check if attribute measurement units are specified

## Priority

- FAIR: Required

## Issues
- No known issues

## Procedure

- fetch each attribute that could have a measurement units specified
- if any such attribute doesn't have units specified, the check fails and a list of offending attributes is returned

**Comment by gothub** [comment]
From @jeanetteclark: regarding entity.attributeUnits.present I think the check should not fail if no attributes require units

**Comment by gothub** [comment]
@jeanetteclark I had a look at the source for this check, and for EML it only checks the following XPaths for units:
```
/eml/dataset/dataTable/attributeList/attribute/measurementScale/interval |
/eml/dataset/dataTable/attributeList/attribute/measurementScale/ratio
```
If those XPaths exist in a document, then they need to have `<units>` defined, or the check fails.
If the document has attributes (i.e. in different entity types: otherEntity, spatialVector, ..) but none require units, the check passes.
If the document doesn't have any attributes at all, then the check fails

Does this seem reasonable?

**Comment by jeanetteclark** [comment]
That sounds right to me.

Hate to beat a dead horse, but are we assuming all entities need attributes? I know we have discussed how to handle this situation before but can't remember if we came up with any solution to the dilemma that some entities don't need attributes (figures, for example).

**Comment by gothub** [comment]
@jeanetteclark I thought this issue was settled but maybe we need to revisit this.

Looking back through the issues, the discussion (lengthy) was [here](https://github.com/NCEAS/metadig-checks/issues/149):

I think that the key issue here is that for any check (in our discussion specifically entity checks), the check can either pass or fail (we are no longer using SKIP). Whether that pass or fail counts toward the score depends on whether the check is OPTIONAL or REQUIRED. The quality engine doesn't have the ability to conditionally make a check OPTIONAL.

So how do we score a document for a check that is looking for a specific element, in this case attribute units, and that document does not have that element (for whatever reason)? It has to either PASS or FAIL, and then be counted or not depending on the OPTIONAL setting.

**Comment by mbjones** [comment]
I agree with Jeanette.  It should not be a failure if units are missing for attributes for which they are inappropriate (nominal, ordinal, and datetime measurement types). The check code can certainly be smart enough to pass in both the measurementType and unit attribute metadata, and only fail if attributes are incorrect for interval and ratio type attributes.  Here's an initial pass at the appropriate responses for the UNIT check:

1. Metadata standard lacks field for unit: FAIL Unit check
2. No attribute metadata in document: FAIL Unit check
3. Attribute info present
    3a. All interval and ratio type attributes have units: PASS
    3b. No attributes are interval or ratio type: PASS
    3c. One or more interval/ratio type attributes lack unit metadata: FAIL

**Comment by gothub** [comment]
@mbjones thanks for the clarification - the steps that you enumerated are exactly what the check is currently doing.
