### ISSUE TITLE
correct typo in resource.abstractLength

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-checks#401]
line 56 here: https://github.com/NCEAS/metadig-checks/blob/master/src/checks/resource.abstractLength.xml seems to have a typo ("abstrac")

I'm also not sure why that XPATH seems to be repeated

**Comment by jeanetteclark** [comment]
https://github.com/NCEAS/metadig-checks/pull/409/commits/caa5668c462b006d05f5a3fdb0054f2856a0c29d

**Comment by mbjones** [comment]
No reason to repeat it. Maybe somebody tried to fix the typo before and ended up duplicating the XPath? One can and should be deleted if they are identical XPaths.

**Comment by gothub** [comment]
Removed duplicate in commit 68476fbee2ca0a7abceccb62238244bb8bfc6b8c, xpath also now spelled correctly.
