### ISSUE TITLE
remove or clarify ambiguous xpaths

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/metadig-checks#404]
There are a number of xpaths scattered throughout the FAIR checks that are ambiguous and don't seem to correspond to a dialect. These should examined, and then either removed or clarified. 

check | xpath
-- | --
resource.abstractLength | /*/description//text()[normalize-space()]
resource.publicationDate.timeframe | /*/available
resource.publicationDate.timeframe | /*/available
metadata.identifier.present | /*/metadataIdentifier/MD_Identifier
resource.creator.present | /*/creator
resource.revisionDate.present | /*/dateSubmitted
entity.identifier.present | /*/identifier
resource.publicationDate.present | /*/available
resource.publicationDate.present | /*/available
resource.titleLength.sufficient | /*/description
resource.titleLength.sufficient | /*/description
resource.spatialExtent.present | /*/spatial
geographic.description.present | /*/spatial
resource.temporalExtent.present | /*/temporal
metadata.identifier.resolvable | /*/metadataIdentifier/MD_Identifier
entity.type.present | /*/type
resource.methods.present | /*/provenance
resource.license.present | /*/rights

**Comment by gothub** [comment]
Fixed in commit 0910b8c56db681a0d0c2c11361bc8892095d08eb
