### ISSUE TITLE
Rename the master branch to main

### ISSUE THREAD

**Issue by csjx** [NCEAS/metadig-checks#410]
From an inclusivity perspective, I suggest we rename the `master` branch to `main` and generally use more welcoming terms as we describe our software architectures. The use of the the terms `master` and `slave` in computing are not welcoming.  For context, see the [Inclusive Naming](https://inclusivenaming.org) project and [this repo](https://github.com/github/renaming).

**Comment by mbjones** [comment]
Done. Working copies can be converted with:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
