### ISSUE TITLE
entity.attributeEnumeratedDomains.present giving false positive

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#413]
The check entity.attributeEnumeratedDomains.present gives a "SUCCESS" status for the [DataCite 4.x 'full' document](https://schema.datacite.org/meta/kernel-4.3/example/datacite-example-full-v4.xml), when instead it should fail.

**Comment by jeanetteclark** [comment]
It looks like in the check code that the case of what to do when `which(!is.na(enumerated_domains))` returns an empty vector, so that might be where this is coming from

**Comment by gothub** [comment]
Fixed in commit 43c1e5f333343cef4a592669f0eff569f846abf9
