### ISSUE TITLE
entity.distributionURL.resolvable

### ISSUE THREAD

**Issue by cgries** [NCEAS/metadig-checks#425]
## Description

entity.distributionURL.resolvable

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Required

## Issues
- This check seems to be implemented inconsistently in DataONE. E.g. this dataset: https://search.dataone.org/view/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fmetadata%2Feml%2Fedi%2F613%2F1 shows all entities to be downloadable. I.e., a distribution URL must have been found and is resolvable, while the FAIR assessment report (https://search.dataone.org/quality/https%3A%2F%2Fpasta.lternet.edu%2Fpackage%2Fmetadata%2Feml%2Fedi%2F613%2F1) says: 'An entity distribution URL was not found' and it's help button says 'Check that the distribution URL is resolvable'. 

## Procedure

Briefly describe the procedure or algorithm to implement the check.

**Comment by mbjones** [comment]
> If the "function" attribute is omitted, then "download" is implied

This is the key phrase. Because of this, then the check should pass when function is ommitted.  But it probably shoud still fail if `function="information"`, as that is not a download URL per se for the entity. Thoughts on that?

**Comment by cgries** [comment]
yes, I agree.

**Comment by gothub** [comment]
Fixed in commit https://github.com/NCEAS/metadig-checks/commit/33b11cf07396236bdcc59997e7564b9585517396.
