### ISSUE TITLE
Quality Report Check: Existing DOI and Alternate Identifier

### ISSUE THREAD

**Issue by emilyarobles** [NCEAS/metadig-checks#427]
## Description

Check that existing DOIs and alternate identifiers in the "Alternate Identifier" field resolve to a dataset landing page.

## Priority

- FAIR: Optional

## Issues
- May only be able to check certain types of identifiers (eg. DOIs)

## Procedure

Check that any identifier included in the Alternate Identifiers field resolves correctly to a dataset landing page. 

## Response for Fail
Warning. The entered DOI is invalid. Enter a valid one or check that it has been reserved.

**Comment by gothub** [comment]
@emilyarobles is this the same as https://github.com/NCEAS/metadig-checks/issues/60?

Also, is it acceptable to have one check for the metadata id and one for the alternate id?
For ESS-DIVE metadata, i've seen different namespaces such as `osti` and `cdiac`. How should these be resolved/checked? 
Here is an example:
-  osti:139493432</alternateIdentifier>

**Comment by emilyarobles** [comment]
@gothub Yes, I believe that we imagined two separate checks (one for the metadata id and one for the alternate id) which is why I created this issue in addition to #60, which would then be the check for the metadata id. 

Are the osti and cdiac examples you are referring to found in the alternate identifier field?

**Comment by gothub** [comment]
Note that this issue references three other issues that might all be used to fulfill the requirements stated in this current issue:
- [metadata.alternateIdentifier.resolvable](https://github.com/NCEAS/metadig-checks/issues/435
) 
- [metadata.identifier.present](https://github.com/NCEAS/metadig-checks/issues/59)
- [metadata.identifier.resolvable](https://github.com/NCEAS/metadig-checks/issues/60)

**Comment by gothub** [comment]
After reviewing the current ESS-DIVE suite, i see that their is a check to verify that a metadata identifier is specified. 
So, I will of course keep that check, but will add an additional check to verity that the identifier resolves.

existing check is 'check.identifier.is.present' (there is no issue for this check).
check to add is [metadata.identifier.resolvable](https://github.com/NCEAS/metadig-checks/issues/60)

**Comment by gothub** [comment]
Added metadata.identifier.resolvable to suite in commit https://github.com/NCEAS/metadig-checks/commit/9f5ce480464f6a16c14604d8199bb456e7d28508
