### ISSUE TITLE
Quality Report Check: File Present

### ISSUE THREAD

**Issue by emilyarobles** [NCEAS/metadig-checks#429]
## Description

Check that at least one data entity is present. 

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Optional - warning

## Issues
- N/A

## Procedure

Return a failed check if dataset has no entities present.

## Response for Failed Check
Warning. No data entities are present.

**Comment by mbjones** [comment]
Is this the same as `check.entity.present` (https://github.com/NCEAS/metadig-checks/issues/126)? If it differs, let's describe how so that we can implement it correctly.

**Comment by gothub** [comment]
Superceded by #126
