### ISSUE TITLE
entity.type.nonproprietary

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#436]
This new check is a variant of the existing check [entity.format.nonproprietary](https://github.com/NCEAS/metadig-checks/issues/64). This new check differs in that the EML element '//otherEntity/entityType` is being checked instead of the element. 
The original check  [entity.format.nonproprietary](https://github.com/NCEAS/metadig-checks/issues/64) will not be modified with this change.
Also, this check is intended only for the ESS-DIVE suite, not for the FAIR suite.

- ESS_DIVE: Required

## Procedure

This check uses the same implementation as https://github.com/NCEAS/metadig-checks/issues/64, but just checks a different element.

**Comment by gothub** [comment]
From Slack, regarding a requested update to this check:
```
[Joan Damerow](https://app.slack.com/team/U01136K3JG1)  [1:33 PM]
Ok. What about this... We can exclude the second check and add a message to the proprietary check: "TIP: If you have not already, upload a csv version for any excel file(s) included."
```

**Comment by gothub** [comment]
This check is now in the ESS-DIVE 1.1.0 suite.

**Comment by emilyarobles** [comment]
The private dataset [https://data.ess-dive.lbl.gov/view/ess-dive-4c81ea45388613e-20220408T203913498](https://data.ess-dive.lbl.gov/view/ess-dive-4c81ea45388613e-20220408T203913498) has 3 CSV files attached, but the entity.type.nonproprietary check is displaying a warning that there is an Excel file included. This check should be passing.

**Comment by gothub** [comment]
@emilyarobles I've discussed this with @Val, that some of the ESS-DIVE metadata files have an incorrect mediaType. For the dataset mentioned above, here is a snippet from the metadata file:
```
    <otherEntity id="ess-dive-815cee323c1b6ed-20220408T204513064">
      <entityName>Koyukuk_River_Floodplain_Soil_Geochemistry.csv</entityName>
      <entityType>application/vnd.ms-excel</entityType>
    </otherEntity>
```

We will discuss this at the tech meeting today to determine a resolution to this problem, which should include identifying all affected metadata files and preventing new metadata from having this problem.

Here is a related metacatui issue:
- Media type is being inserted into ./otherEntity/entityType element
  - https://github.com/NCEAS/metacatui/issues/1951

**Comment by Val** [comment]
@gothub please stop beeping me using @Val it's annoying
