### ISSUE TITLE
Enhance resource.projectTitle.controlled-1.0.0 to use the new ESS-DIVE Mule service

### ISSUE THREAD

**Issue by vchendrix** [NCEAS/metadig-checks#438]
## Description

Enhance the ESS-DIVE suite check for projects names (`resource.projectTitle.controlled-1.0.0`) to get the project names from the new Mule service.  The test api can be found at https://mule.ess-dive.lbl.gov/project/.  This service should be up be COB 3/8/2022.  In the meantime you can test against https://mule-stage.ess-dive.lbl.gov/project/.

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Required

**Comment by mbjones** [comment]
The API endpoint listed in #440 seems to work for me (and changed from the one initially posted in this issue):

https://mule.ess-dive.lbl.gov/api/project/
