### ISSUE TITLE
entity.attributeName.differs

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#44]
## Description

Check if the entity name is the same as the entity description, i.e. did the metadata author cut/paste the entity name into the description.

## Priority

- FAIR: Required

## Issues
- no known issues

## Procedure

- for each attribute, check that the name and description are not equivalent. If any attributes don't pass this check, the check fails and the non-compliant entity names are listed.

**Comment by gothub** [comment]
Note that this check is similiar to https://github.com/NCEAS/metadig-checks/issues/119, and that when appropriate, these two checks should be merged into one.

**Comment by JEDamerow** [comment]
Same as implemented check #119 ?
