### ISSUE TITLE
resource.geographic.description.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#45]
## Description

Check if a dataset geographic description is present.

## Priority

- FAIR: Required

## Issues
- No known issues

## Procedure

- if a geographic description is not present, the check fails.

**Comment by tedhabermann** [comment]
Should this check for a spatial keyword as well as a spatial description if both exist in the dialect?

**Comment by JEDamerow** [comment]
What about datasets where a geographic description is not relevant, like laboratory studies? As mentioned for vertical extent issue, is there any good way to indicate whether certain elements are relevant for a particular dataset?

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[*].attributes.geoLocations[*].geoLocationPlace

**Comment by gothub** [comment]
This check had an unnecessary option set on the XPath selector which has been removed in
commit 93ce3d881aaf6a60b359b6376e5471d0af46bbe9. This extra selector should not have any negative effect.
