### ISSUE TITLE
Project Name within Controlled List Check Failing incorrectly

### ISSUE THREAD

**Issue by dylanporyan** [NCEAS/metadig-checks#456]
## Description
The "Resource Project Title Controlled" check within some ESS-DIVE assessment reports has failed when it should not. The check will sometimes issue a warning when the project title is in fact in our [controlled list of projects](https://data.ess-dive.lbl.gov/projects).

## Priority

- FAIR: Optional

## Examples
- Failed check, yet the project "From tides to seasons: How cyclic tidal drivers and plant physiology interact to affect carbon cycling at the terrestrial-estuarine boundary" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-11685f5a347bc70-20240529T031255831
- Failed check, yet the project "Plant Carbohydrate Depletion, Mycorrhizal Networks, and Vulnerability to Drought: An Experimental Test in the Field" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-602325bcf389cf4-20240514T194603622
- Failed check, yet the project "Belowground Biogeochemistry Scientific Focus Area" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-ca5a51cbccf1e16-20231019T130141667
- Failed check, yet the project "Functional-type modeling approach and data-driven parameterization of methane emissions in wetlands" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-f1ce2584ab32e53-20240430T190615777
- Failed check, yet the project "ORNL Terrestrial Ecosystem Science SFA" is in our project list: https://data.ess-dive.lbl.gov/quality/ess-dive-c98cca127f51a94-20240424T173339594

**Comment by jeanetteclark** [comment]
Thanks for the report and examples. It actually looks like the check was not updated to read the correct file even though the file is available (see discussion of this over in https://github.com/NCEAS/metadig-checks/issues/440). I updated that and will test on the dev cluster before deploying. This will be easy to loop into a few other changes to the ESS-DIVE suite

**Comment by jeanetteclark** [comment]
This has been fixed and tested with replicas of the original datasets on the dev cluster
