### ISSUE TITLE
entity.checksum.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#47]
## Description

Check that each data entity has a checksum specified.

## Priority

- FAIR: Required

## Issues
- No known issues

## Procedure
- for each data entity listed in the metadata, check that a checksum is specified. If any entities do not, then the check fails and the non-compliant entities are listed.

**Comment by kaiiam** [comment]
From my experiences, I believe this is a very good, easy and verifiable test, making sure the checksum matches to ensure interoperability and reuse of the data product.
