### ISSUE TITLE
resource.keywords.controlled.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#48]
## Description

Check if keywords are controlled by a vocabulary.

## Priority

FAIR: Optional

## Issues
- No known issues

## Procedure

- for each group of keywords, check if a thesaurus has been specified. 
- no check is made regarding the authority of the vocabulary, i.e. is a URL specified and does it resolve.

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[*].attributes.subjects[*].subjectScheme. If a subjectScheme exists, it indicates that the keywords come from that scheme.

**Comment by gothub** [comment]
Added to ESS-DIVE suite in commit 583d381d95b5765160e578a9fa8114b0630712b7

@JEDamerow each check has it's own default level (REQUIRED, OPTIONAL, INFO) and type (Accessible, Findable, ...) which is defined in the check XML file. These can be overridden for a suite by modifying the suite XML file, for example https://github.com/NCEAS/metadig-checks/blob/dev-0.2.0/src/suites/ess-dive.xml, shows the `dataset.keywords.controlled` entry with values that will override the check defaults.
