### ISSUE TITLE
resource.methods.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#53]
## Description

Check if a detailed methods (for data collection, experiment design, etc.) section exists.

## Priority

- FAIR: Required

## Issues
- No known issues 

## Procedure

- check if a methods section exists, and if not, the check fails.

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[\*].attributes.descriptions[?(@.descriptionType="Methods")].description
