### ISSUE TITLE
entity.attributeEnumeratedDomains.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#56]
## Description

Check entity attribute measurement scales for enumerated domains

## Priority

Choose a priority for the FAIR suite (Required or Optional)

- FAIR: Required

## Issues
- ISO 19115 does not have this concept. Should this check be included in FAIR?

## Procedure

- for attributes that can have enumerated domains specified (e.g. EML nominal, ordinal), check if an enumerated domain is specified. If not, then the check fails and non-compliant attributes are listed.

**Comment by JEDamerow** [comment]
@gothub Is this the same as #141?
