### ISSUE TITLE
resource.keywords.type.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#57]
## Description

Check if keywords have a type specified

## Priority

FAIR: Optional

## Issues
- No known issues

## Procedure
- for each group of keywords, check if a keyword type has been specified. 
- the authority of the keyword type specified is not check - it is not inspected to see if it is a URL (or resolvable id).

**Comment by tedhabermann** [comment]
Keyword Type is distinct from Keyword Vocabulary. It is a category, not a shared vocabulary. For example, in ISO 19115-1 keyword types are: discipline, place, stratum, temporal, theme, dataCentre, featureType, instrument, platform, process, project, service, product, subTopicCategory, taxon.

**Comment by gothub** [comment]
@tedhabermann yes, for ISO we are checking `/*/identificationInfo/*/descriptiveKeywords/MD_Keywords/type/MD_KeywordTypeCode`.

I'm assuming that any keyword type specified is acceptable, and not a subset of those listed at https://geo-ide.noaa.gov/wiki/index.php?title=ISO_19115_and_19115-2_CodeList_Dictionaries#MD_KeywordTypeCode
