### ISSUE TITLE
resource.license.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#61]
## Description

Check if a clear and accessible metadata usage license is specified

## Priority

FAIR: Required

## Issues
- the description of this check stats 'an accessible usage license'. Should this check be evaluating the license type, possibly against a controlled list, i.e. from https://spdx.org/?

## Procedure

- check if a license is present
- (potentially) - check if the license is known to a well known authority (i.e. SPDX)

**Comment by JEDamerow** [comment]
Similar to implemented check #137 ?

**Comment by gothub** [comment]
For EML, use either '<intellectualRights>' or EML 2.2 '<licensed>'
