### ISSUE TITLE
resource.keywords.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#63]
### ## Description

Check if keywords exists that are not controlled by a vocabulary

## Priority

FAIR: Required

## Issues
- No knows issues

## Procedure

- for each keyword group, check if any keywords exist, controlled or not controlled
- if no such keyword groups are found, the check fails

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[*].attributes.subjects[*].subject

**Comment by JEDamerow** [comment]
How would this check affect a FAIR score? What makes more sense to me is to have check for a minimum number of keywords. For example, many journals have a minimum of 3-6 keywords, and require that the keywords must differ from the title.

**Comment by gothub** [comment]
This check is being modified to check if any keywords exist, and will be a required check.

There are currently 2 keyword checks for FAIR, one that checks for controlled keywords and one that checks for 'natural language' keywords. Since a metadata file will probably not have both, at least one of these checks will fail.

The proposed modification would make the basic check 'resource.keywords.present' required and 'resource.keywords.controlled' as optional. The basic, required check will pass if either controlled or natural language keywords are present.

(Note that some FAIR checks are being renamed, as detailed in #156
