### ISSUE TITLE
resource.creator.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#69]
## Description

For creator: check presence, affiliation, email, significant name

## Priority

- FAIR: Required

## Issues
- what is a creator significant name?

## Procedure

- check that a creator and all required sub-fields are present and if they are all found, the check passes

**Comment by tedhabermann** [comment]
The target for this check is a **mandatory field** in the DataCite Dialect. The name of the creator can be implemented in several ways: data[*].attributes.creators[*].name, data[*].attributes.creators[*].givenName, and data[*].attributes.creators[*].familyName. 

The creator can also have two nameTypes: Personal (default) and Organizational

**Comment by tedhabermann** [comment]
Affiliation information is separate from responsibleParty names in most dialects and it should be a separate check. I created https://github.com/NCEAS/metadig-checks/issues/145 for affiliation

**Comment by JEDamerow** [comment]
same as implemented check #123
