### ISSUE TITLE
resource.creator.identifier.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#70]
## Description

Check that the dataset creator has an identifier specified (i.e. ORCID)
## Priority

- FAIR: Required

## Issues
- should this check be optional?

## Procedure

- if the dataset creator identifier is present, the check passes

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[*].attributes.creators[*].nameIdentifiers[*].nameIdentifier
