### ISSUE TITLE
entity.identifier.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#77]
## Description

Check if each data entity has an identifier
## Priority

- FAIR: Required

## Issues
- no known issues

## Procedure

- check that each data entity has an identifier
- if any entities do not have ids, the check fails and the non-compliant entities are listed.

**Comment by tedhabermann** [comment]
The target for this check is a **mandatory field** in the DataCite Dialect: data[*].attributes.doi and data[*].attributes.identifiers[*].identifier.
