### ISSUE TITLE
entity.identifier.type.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#79]
## Description

For each data entity, check that an identifier and type are present

## Priority

- FAIR: Optional

## Issues
- List of issues to be resolved

## Procedure

- for each data entity, extract the identifier and type
- if any entity identifiers do not have types, then the check fails and the non-compliant entities are listed

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data[*].attributes.identifiers[*].identifierType. It is mandatory and "DOI" in all cases.
