### ISSUE TITLE
resource.date.publication.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#82]
## Description

Check if the dataset has a publication date

## Priority

- FAIR: Required

## Issues
- no known issues

## Procedure

- check that a publication date is present and if not, the check fails.

**Comment by tbs1979** [comment]
The date fields should have a format check to see if the date is consistent and parseble

**Comment by JEDamerow** [comment]
What if the publication date is 20 or 50 years from now? Maybe this check should be for past or present date, instead of a presence check.

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite dialect: data.attributes.publicationYear

**Comment by JEDamerow** [comment]
Same as implemented check #134
