### ISSUE TITLE
resource.publisher.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#83]
## Description

Check if a publisher is present

## Priority

- FAIR: Required

## Issues
- what is being evaluated when checking for `significant name`?
- how to check for organization id?

## Procedure

- extract the publisher if present, if not then the check fails
- evaluate for `significant name`, `organization id`

**Comment by tedhabermann** [comment]
The target for this check is a **mandatory field** in the DataCite Dialect: data[*].attributes.publisher. it exists in virtually all records.

**Comment by tedhabermann** [comment]
I think this test belongs in the Findable Suite, not Accessible.

**Comment by gothub** [comment]
@tedhabermann I updated the label, but I'm just wondering what was the argument for putting this in `Accessible`, as this was the first item under `Accessible` from our March workshop.
