### ISSUE TITLE
entity.type.present check

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#86]
## Description

For each data entity, check if a type is specified

## Priority

- FAIR: Required

## Issues
- EML doesn't appear to differentiate between format and type, so there may be overlap between this check and `entity.format.present`

## Procedure

- for each entity, check for the presence of a type

**Comment by cscully-allison** [comment]
EML does differentiate between format and type so there is not an overlap between this check and entity.format.present.

**Comment by gothub** [comment]
@cscully-allison thx - yep, the EML entity `type` to check for is one of `dataTable`, `otherEntity`, `spatialRaster`, `spatialVector`, `storedProcedure`, `view`.

**Comment by gothub** [comment]
The XPath expression for this check could use the XPath `name()` function to identity the EML entity type present, but this isn't supported by the Java XPath 1.0 implementation. The workaround is to just check for the presence of the element, without returning the name (e.g. `dataTable` found), which would appear in the check output.

See https://github.com/NCEAS/metadig-engine/issues/219

**Comment by gothub** [comment]
Superceded by #146
