### ISSUE TITLE
resource.spatialExtent.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#92]
## Description

Check if a spatial extent has been specified

## Priority

- FAIR: Optional

## Issues
- no known issues

## Procedure

- check for the presence of a spatial extent element

**Comment by JEDamerow** [comment]
What about associated coordinate system?

**Comment by mbjones** [comment]
Spatial extents for bounding coordinates in all major metadata standards are specified as geocoordinates in lat and lon, and so do not have a spatial reference system.  They also usually have more detailed sections with spatial reference sections for specific data entities, but these don't typically apply to the bounding coordinates.  For example, there is no spatial reference system for the `geographicCoverage` field in EML.  So, I think this is a non-issue.  Please clarify if you mean something different than how I am interpreting this.

**Comment by JEDamerow** [comment]
Similar to #127 and #45 spatial extent is another important element where it may not be applicable for certain datasets (e.g. lab studies). I guess this could be somewhat covered in being Optional. But, spatial extent is also really important for datasets where location is relevant. One option could be to have a way for users to explicitly indicate that certain key fields are not relevant for their dataset. Or any explicit conditions for use of the check should likely be focused on data types where spatial extent is NOT relevant in this case (e.g. lab studies, non-spatial modeling).

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: 
`"geoLocations": [{
            "geoLocationBox": {
                "eastBoundLongitude": "114",
                "northBoundLatitude": "26",
                "southBoundLatitude": "25",
                "westBoundLongitude": "112"
            },
            "geoLocationPoint": {
                "pointLatitude": "26",
                "pointLongitude": "112"
            },
            "geoLocationPolygon": [
                {"polygonPoint": {
                    "pointLatitude": "29.632185",
                    "pointLongitude": "-95.622993"
                }},
                {"polygonPoint": {
                    "pointLatitude": "29.641747",
                    "pointLongitude": "-95.084487"
                }},
                {"polygonPoint": {
                    "pointLatitude": "30.111985",
                    "pointLongitude": "-95.094293"
                }},
                {"polygonPoint": {
                    "pointLatitude": "29.641747",
                    "pointLongitude": "-95.084487"
                }}
            ],
            "geoLocationPlace": "geoLocationPlace"
        }]`

**Comment by JEDamerow** [comment]
same as implemented check #120
