### ISSUE TITLE
resource.temporalExtent.present

### ISSUE THREAD

**Issue by gothub** [NCEAS/metadig-checks#94]
## Description

Check if a temporal extent is present

## Priority

- FAIR: Optional

## Issues
- no known issues

## Procedure

- check if a temporal extent element is present, and if not, the check fails

**Comment by JEDamerow** [comment]
Same or similar to deployed check: check.temporal.coverage.1.

What about dates provided in standard format?

**Comment by mbjones** [comment]
I would argue that is a separate check, especially as there is no universal format that all countries and disciplines use.  For datasets in modern times, an ISO 8601-compatible date might be preferred. This is typically enforced in some XML schemas.  For geologic-scale temporal coverages, there are many more valid formats in widespread use, including various estimates of years before present and various named stratigraphic systems, among others.

**Comment by JEDamerow** [comment]
Yes, it makes sense to be a separate interoperability check.

**Comment by tedhabermann** [comment]
The target for this check exists in the DataCite Dialect: data.attributes.dates[?(@.dateType="Collected")].date
